name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Create Apps Script Project ID
        run: |
          python .github/workflows/publish.py --script_id=${{ secrets.APPS_SCRIPT_PROJECT_SCRIPT_ID }}

      - name: Apps Script Credentials 🛎
        uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: ${{ secrets.APPS_SCRIPT_CLIENT_ID }}
          client-secret: ${{ secrets.APPS_SCRIPT_CLIENT_SECRET }}
          refresh-token: ${{ secrets.APPS_SCRIPT_REFRESH_TOKEN }}
        
      - name: Install Yarn
        run: |
          yarn install

      - name: Publish new version 🚀
        run: |
          yarn publish-project
